config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'dashboard', to: 'dashboard#index'

  resources :devs, only: [ :index, :show, :new, :create, :destroy, :myprofile ] do
    resources :bookings, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :dev
  belongs_to :user

  validates :date_on, uniqueness: true

end

app/models/dev.rb
class Dev < ApplicationRecord
  belongs_to :user
  has_many :bookings

  has_one_attached :avatar

  validates :name, presence: true
  validates :city, presence: true
  validates :age, presence: true
  validates :language, presence: true
  validates :price_per_day, presence: true

  def unavailable_dates
    bookings.pluck(:date_on)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :devs, dependent: :destroy
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @user = User.find(params[:id])
    if @booking.user_id == @user
      @bookings = Booking.all
    end
  end

  def new
    @booking = Booking.new
  end

  def create
    @dev = Dev.find(params[:dev_id])
    @booking = Booking.new(booking_params)
    @booking.dev = @dev
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render 'devs/show', status: :unprocessable_entity
    end
  end

  private

  def destroy
    @booking.destroy
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date_on)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/devs_controller.rb
class DevsController < ApplicationController
  before_action :set_dev, only: [ :show, :destroy ]

  def index
    @devs = Dev.all
  end

  def show
    @booking = Booking.new
  end

  def new
    @dev = Dev.new
  end

  def create
    @dev = Dev.new(dev_params)
    @user = current_user
    if @dev.save
      redirect_to dev_path(@dev)
    else
      render 'new'
    end
  end

  def destroy
    @dev.destroy
  end


  private

  def set_dev
    @dev = Dev.find(params[:id])
  end

  def dev_params
    params.require(:dev).permit(:name, :age, :city, :language, :disponibility, :price_per_day, :rating, :avatar_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end

  def search
    if params[:query].blank?
      redirect_to root_path and return
    else
      @parameter = params[:query].downcase
      @results = Dev.all.where('lower(profile) LIKE :search', search: "%#{@parameter}%")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h1>Bonjour</h1>

app/views/dashboard/index.html.erb
<div class="dashboard">
  <div>
    <h1>Mon dashboard</h1>
  </div>

  <div class="mesdevs">
    <h3>Ma team</h3>
  </div>

  <div class="container">

    <% current_user.devs.each do |dev| %>
      <%= link_to dev_path(dev) do %>
      <div class="zoom">
        <h4><%= dev.name %></h4>
        <%= cl_image_tag dev.avatar.key %>
      </div>
      <% end %>
      <ul>
        <% dev.bookings.each do |booking| %>
          <%= booking.date_on %>: <%= booking.user.email %>
        <% end %>
      </ul>
    <% end %>
  </div>


  <div class="mesresa">
    <h3>Mes reservations</h3>
  </div>
  <div class="container">
      <% current_user.bookings.each do |booking| %>
          <div class="zoom">
        <%= booking.date_on %>: <%= booking.dev.name %>
        <%= cl_image_tag booking.dev.avatar.key %>
      </div>
    <% end %>
   </div>
</div>

app/views/devs/index.html.erb
<div class="title">
  <h1 >Pas les plus connus mais les plus compétents</h1>
  </div>
  <br>
  <div class="container">
  <ul class="cards">
    <% (@devs).each do |dev| %>
      <li>
        <%= link_to dev_path(dev) do %>
          <div class="card-trip", >
            <%= cl_image_tag dev.avatar.key, width: 150, height: 150, crop: :fill %>
            <div class="card-trip-infos">
              <h2><%= dev.name %></h2>
              <h2><i class="fa fa-address-card"></i> <%= dev.profile %></h2>
              <h2><i class="fa fa-sitemap"></i> <%= dev.language %></h2>
              <h2><i class="fa fa-star"></i> <%= dev.rating %>/5</h2>
              <h2 class="card-trip-pricing"><%= dev.price_per_day%>€ /jour</h2>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/devs/new.html.erb
<%= simple_form_for(@dev) do |f| %>
  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :city %>
  <%= f.input :language %>
  <%= f.input :price_per_day %>
  <%= f.input :avatar, as: :file %>
  <%= f.submit %>
<% end %>

app/views/devs/show.html.erb
<div class="show">
<div class="cards">
  <div class="card-trip">
    <%= cl_image_tag @dev.avatar.key, width: 150, height: 150, crop: :fill %>
    <div class="card-trip-infos">
      <div>
        <h2><%= @dev.name %></h2>
          <p><i class="fa-solid fa-address-card"></i> <%= @dev.profile %></p>
          <p><i class="fa-solid fa-sitemap"></i> <%= @dev.language %></p>
          <p><i class="fa-solid fa-star"></i> <%= @dev.rating %>/5</p>
          <p>âge : <%= @dev.age%> ans. ville : <%= @dev.city%></p>
      </div>
        <h2 class="card-trip-pricing"><%= @dev.price_per_day%>€/jour</h2>
    </div>
    <div>
      <% if current_user == @dev.user_id %>
      <%= link_to "Supprimer", dev_path(@dev), class:"btn btn-link text-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      <% end %>
    </div>
  <%= link_to "Retour", devs_path, class:"btn btn-success"%>
  </div>

  <%# <div>
    <h3>Réserver vote date</h3>
      <%= simple_form_for([@dev, @booking]) do |f| %>
        <%# <%= f.input :date_on %>
        <%# <%= f.submit 'Réserver', class:"btn btn-success"%>
      <%# <% end %>
  <%# </div> %>
<%# </div> %>


  <div>
    <h3>Réservez votre dev'date</h3>
      <%= simple_form_for ([@dev, @booking]), data: { controller: 'flatpickr', flatpickr_unavailable_value: @dev.unavailable_dates } do |f| %>
        <%= f.input :date_on, as: :hidden, input_html: { data: { flatpickr_target: "dateOn" } } %>
        <%= f.submit 'Réserver', class:"btn btn-success" %>
    <% end %>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tindev</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'shared/navbar' %>

   
      <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
  <div class="container">
    <div class="autre">
      <h1 >Laissez-vous accompagner dans vos projets.</h1>
      <p>Avec Tindev, des millions de Dev' à portée de clic qui n’attendent plus que de rencontrer quelqu’un comme vous.</p>
    </div>

    <div class= "search-block">
      <div class= "search-tab">
        <%= form_with url: devs_path, method: :get do |form| %>
          <%= form.text_field :query, placeholder: "Spécialité ?", class: "border border-light p-1" %>
          <%= form.text_field :city, placeholder: "Quelle ville ?", class: "border border-light p-1" %>
          <%= form.submit "Recherche", class: "btn" %>
        <% end %>
      </div>
    </div>
    <br><br>
    <div class="disco">
   <%= link_to ">> Découvrir tous les devs ", devs_path %>
    </div>
  </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div>
      <%= link_to root_path do  %>
        <span class="logo"><%= image_tag 'logo.svg' %></span>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if current_user %>
        <li class="nav-item">
          <%= link_to dashboard_path, class: "logoprofil" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
          <% end %>
        </li>
          <li class="nav-item active">
             <%= button_to "Me déconnecter", destroy_user_session_path, data: { turbo: false }, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item active">
             <%= link_to "Me connecter", user_session_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Créer un compte", new_user_registration_path(@user), class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    Tindev
    <h1 class="text-center"><%= "Welcome Yoann" %></h1>
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <%= form_with url: "/search", method: :get do |form| %>
            <%= form.text_field :query, placeholder: "Search" %>
            <%= form.submit "Search", class: "btn btn-outline-success" %>
            <%= link_to "Add Dev", "#", class: "btn btn-outline-primary" %>
          <% end %>
          <%#= link_to "Add Dev", new_Dev_path, class: "btn btn-outline-primary" %>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>

    </div>
  </div>
</div>


<div class="container">
<div class="cards">
  <h1>All our Devs</h1>
  <br>
  <ul class="cards">
    <% (@user.devs).each do |dev| %>
    <li><div class="card-trip">
      <%= cl_image_tag dev.avatar.key, width: 150, height: 150, crop: :fill %>
        <div class="card-trip-infos">
          <div>
            <h2><%= dev.name %></h2>
              <p><%= dev.profile %></p>
              <p><i class="fa-solid fa-people-roof"></i><%= dev.language%></p>
          </div>
            <h2 class="card-trip-pricing"><%= dev.price_per_day%>€</h2>
          </div>
        </div>
    </li>
    <% end %>
  </ul>
</div>
</div>